### PR TITLE
Added a parser for string -> double and method to replace , -> .

### PR DESCRIPTION
**Pull request by Ugniusst**
So I added a new class, where we can store static methods for data conversions. This time I added parser for double, so we can get 3.14 from "pi number is 3,14 and so on".

### CODE REVIEW

**Comment by Tomas-Per** [comment]
There shouldn't be a Main method in this class, to make it more akin to a class library, since the entry point for the program won't be here

**Comment by Ugniusst** [comment]
> There shouldn't be a Main method in this class, to make it more akin to a class library, since the entry point for the program won't be here

The problem is that if DataContent doesn't have any Main class (entry point) it will always show the error that it is missing an entry point. 
image

**Comment by Ugniusst** [comment]
> > There shouldn't be a Main method in this class, to make it more akin to a class library, since the entry point for the program won't be here
> 
> The problem is that if DataContent doesn't have any Main class (entry point) it will always show the error that it is missing an entry point.
> image

I Found the problem, will fix it soon

**Comment by Tomas-Per** [comment]
You can change the output type from application to class library. Project>Properties>Output Type

**Review by Tomas-Per — APPROVED** [review]
Looks good

**Pull request merged**
